### ISSUE TITLE
Possibility to get CCd eMails too?

### ISSUE THREAD

**Issue by vdbhb59** [CicadaCinema/get-all-senders#1]
👋
As per the subject line, is there a possibility to extract the CCd lists as well, in a CCd column/list separately?
Just wondering, as that might assist.

Danke. 😃

**Comment by CicadaCinema** [comment]
Yes, I will add this feature, but I am pretty busy right now. Ironically the UI will take the most time.

Reference: https://webextension-api.thunderbird.net/en/latest/messages.html#messages-messageheader

If you really need this you can replace [these](https://github.com/CicadaCinema/get-all-senders/blob/4dc7563f96adfdfcf4c022bf8ecdb89d85f3806a/mainPopup/popup.js#L15) [two](https://github.com/CicadaCinema/get-all-senders/blob/4dc7563f96adfdfcf4c022bf8ecdb89d85f3806a/mainPopup/popup.js#L22) lines with the following:
```javascript
message.ccList.forEach(ccString => senders.add(ccString))
```

By making this change you will essentially turn this extension into get-all-cc.

**Comment by vdbhb59** [comment]
Thanks, let me check this out on my end. Will revert soon.

**Comment by mabox965** [comment]
hello,
thanks for your addon 👍 
following the [message above](https://github.com/CicadaCinema/get-all-senders/issues/1#issuecomment-1505996910), I've modified the popup.js.
in results, some cc doesn't appears ?
what can I do ?
thanks

**Comment by vdbhb59** [comment]
Sorry, I meant to get back earlier, kind of slipped my mind.
I tried, and cc does appear, but many get missed out randomly.
I will try the changed code once again tomorrow and get back once more.

**Comment by CicadaCinema** [comment]
@mabox965 @vdbhb59 

Hello.

I'm sorry that the change I suggested doesn't work for you. It appears to work on my mailbox, but I have very few messages with cc recipients.

Right now I can't think of a reason why some messages would be getting skipped, so please help me to debug this.

You can [download](https://github.com/CicadaCinema/get-all-senders/raw/get-all-cc/get-all-senders-get-all-cc.zip) a zip file for testing which I assume you have been loading as a "Temporary Add-on".

For testing on your own computer, please follow the steps below to provide me with as much information as possible on the issue:
- load the add-on as a "Temporary Add-on"
- beside the 'Get all senders' name, click 'Inspect' and ensure that 'Errors', 'Warnings', 'Logs', 'Info' and 'Debug' are all enabled in the top right of the tab that appears.
- go back to the tab with your mailbox and click on the add-on, wait until it finishes running
- go to the tab with the logging window, copy all the lines that have appeared, and expand any subsections if there is such an option. this may be helpful for me to debug the issue
- if you can, find examples of email messages where the cc is being extracted correctly, and examples of messages where the cc is being omitted by my add-on. in the top-right, click "view source" and copy the text from the window that appears for each of these emails, redacting any personal information (you can probably redact any long string tokens, URLs or email addresses, as long as I can tell where two redacted addresses are the same and where they are different). Maybe you can find the difference yourself in these two strings of text, inspecting the lines close to the cc field, since this is what you are interested in.

If it's possible, maybe you could provide me with a sample email or two so that I can debug this myself:
- create a new Thunderbird profile (see [here](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-thunderbird-profiles) for more information)
- load the email account with the problematic messages
- find an example of an email, which contains a cc field that is missed out by my modified extension (hopefully you can find one with as little personal identifying information as possible)
- delete all other emails
- use an add-on such as [ImportExportTools NG](https://addons.thunderbird.net/en-us/thunderbird/addon/importexporttools-ng/) to produce a .mbox file which you can send to me for review. I will delete it and any traces of your email conversations when I am done with debugging this issue.

**Comment by CicadaCinema** [comment]
I can be reached privately at the following address:

I have split up my contact address into two parts - before and after the @ symbol.

<details>
  <summary>Click to expand</summary>

github-contact
</details>

(@ symbol)

<details>
  <summary>Click to expand</summary>

arseny.uk
</details>

**Comment by vdbhb59** [comment]
It is working now, and all CCd email ids are getting fetched too.
Previously (6-7 days back, I think, the email ids were getting randomly missed out).
I will keep you posted in a week's time, if there is any issue on this. :)

Edit: 06.06.2023 - Works as should. In case I face issue again, I will revert.
Thanks again mate. 👍

**Comment by CicadaCinema** [comment]
I am very happy that my add-on is useful to you!

**Comment by mabox965** [comment]
Hello @CicadaCinema,
it is works perfectly without any issue 👍
bravo 😃 & merci

**Comment by CicadaCinema** [comment]
> Hello @CicadaCinema, it is works perfectly without any issue 👍 bravo 😃 & merci

I'm happy that it works for you :)
